### ISSUE TITLE
Make JCommunique available on Maven Central or JCenter

### ISSUE THREAD

**Issue by lpellegr** [spfrommer/JCommunique#1]
It would be really convenient to have JCommunique available on [Maven Central](http://central.sonatype.org/pages/ossrh-guide.html) or [JCenter](https://bintray.com/bintray/jcenter). This way, people who use Maven, Gradle, etc. can configure their project to use JCommunique in 3 seconds.

**Comment by spfrommer** [comment]
Thanks for mentioning this. I'll look into it.

**Comment by spfrommer** [comment]
Is there any way for me to do this without re configuring my project as a Maven / Gradle build system? I'm happy with what I have now.

**Comment by spfrommer** [comment]
JCommunique 2.0.0 is now on JCenter.
https://bintray.com/spfrommer/maven/jcommunique/view
