### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by 99-bottles** [spfrommer/JCommunique#2]
I've found a couple of memory leaks. 

The first is in the WindowNotification. The JWindow never has dispose() called on it, so Swing will retain a reference (and related resources) forever. I'd suggest calling dispose() from hide(). 

The second is in SimpleNotificationManager. If you enable fading, the Fader task will be retained by the Timer, which in turn means the Notification is retained after hide() is called. I think it's probably inappropriate to use a non-Swing timer here, given that you're doing UI operations. One way to fix the leak would be to have a small manager class that holds the Faders while fading is in progress, and remove them when they are done. A Swing Timer could then call your Fader manager. 

For better performance on laggy systems, I'd also suggest that Fader should use the current time to determine how opaque the notification should be, rather than requiring a fixed number of calls. As it stands, if the system is under load, the user has to wait for each "step" to render.

I've found these fairly straightforward to reproduce by creating WindowNotifications periodically with a Swing Timer, passing them to a QueueNotificationManager and waiting for the rendering to become jerky. It only took 50 or so notifications before things became sluggish for me (obviously system-dependant). If you monitor garbage collection, you'll find the JWindows never get reclaimed.

**Comment by spfrommer** [comment]
Hi @99-bottles,

Thanks for letting me know and taking the time to open such a detailed issue. I'll have these fixed up this weekend.

**Comment by spfrommer** [comment]
@99-bottles: Might take a few more days actually---quite busy right now.

**Comment by spfrommer** [comment]
I fixed the dispose() issue, but am having some confusion with the Fader memory leaks. In the old system, the Faders were never garbage collected, and neither were their Notifications. After my update implementing your suggestions, the Faders are collected, but the JWindows are not, even after dispose() is called and no references are held. Perhaps this could be best illustrated with a simple test:

```
public class TestDemo {
	public static void test() {
		JFrame frame = new JFrame();
		frame.setSize(500, 500);
		frame.setVisible(true);
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		frame.dispose();
		frame = null;

	}

	public static void main(String[] args) {
		test();
		try {
			Thread.sleep(1000000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
	}
}
```

During the second sleep(), I manually perform a garbage collection in the memory analyzer; however, the JWindow instances are still not reclaimed. Any ideas?

**Comment by 99-bottles** [comment]
Sorry I didn't respond earlier, I missed the email. 

I think what you're seeing is probably due to the way the garbage collector works. Requesting it to collect garbage is treated more are a friendly suggestion than a command; because swing interacts with native resources things probably get a bit more complicated/unpredictable. You can force the issue by writing a loop which creates new JWindows every second. You should find that not disposing them results in an OutOfMemoryError. If you override finalize() and print something out, once you add a call to to dispose() you should see old instances get finalized in batches as the heap space starts filling up with garbage.

**Comment by spfrommer** [comment]
That makes sense, thanks for the clarification!
