### ISSUE TITLE
for maven it is not working

### ISSUE THREAD

**Issue by Ethosteck** [spfrommer/JCommunique#4]
while adding dependency not working

**Comment by spfrommer** [comment]
Could you please add more description?

**Comment by Ethosteck** [comment]
i am reinstalling and will follow each step i will let you know if any
issue arises.

thanks a lot for replying

**Comment by jmulder31** [comment]
Doesn't work with the provided maven code. I had to use the following direct from the maven repo:

<dependency>
            <groupId>com.github.lespaul361</groupId>
            <artifactId>JCommunique</artifactId>
            <version>2.0.0</version>
        </dependency>
